<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/errors/null_error.proto

namespace GPBMetadata\Google\Ads\GoogleAds\V1\Errors;

class NullError
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a93030a2f676f6f676c652f6164732f676f6f676c656164732f76312f65" .
            "72726f72732f6e756c6c5f6572726f722e70726f746f121e676f6f676c65" .
            "2e6164732e676f6f676c656164732e76312e6572726f7273224c0a0d4e75" .
            "6c6c4572726f72456e756d223b0a094e756c6c4572726f72120f0a0b554e" .
            "5350454349464945441000120b0a07554e4b4e4f574e100112100a0c4e55" .
            "4c4c5f434f4e54454e54100242e9010a22636f6d2e676f6f676c652e6164" .
            "732e676f6f676c656164732e76312e6572726f7273420e4e756c6c457272" .
            "6f7250726f746f50015a44676f6f676c652e676f6c616e672e6f72672f67" .
            "656e70726f746f2f676f6f676c65617069732f6164732f676f6f676c6561" .
            "64732f76312f6572726f72733b6572726f7273a20203474141aa021e476f" .
            "6f676c652e4164732e476f6f676c654164732e56312e4572726f7273ca02" .
            "1e476f6f676c655c4164735c476f6f676c654164735c56315c4572726f72" .
            "73ea0222476f6f676c653a3a4164733a3a476f6f676c654164733a3a5631" .
            "3a3a4572726f7273620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

