<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v23/resources/location_view.proto

namespace GPBMetadata\Google\Ads\GoogleAds\V23\Resources;

class LocationView
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();
        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Resource::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xCC\x04\x0A6google/ads/googleads/v23/resources/location_view.proto\x12\"google.ads.googleads.v23.resources\x1A\x19google/api/resource.proto\"\xC4\x01\x0A\x0CLocationView\x12D\x0A\x0Dresource_name\x18\x01 \x01(\x09B-\xE0A\x03\xFAA'\x0A%googleads.googleapis.com/LocationView:n\xEAAk\x0A%googleads.googleapis.com/LocationView\x12Bcustomers/{customer_id}/locationViews/{campaign_id}~{criterion_id}B\x83\x02\x0A&com.google.ads.googleads.v23.resourcesB\x11LocationViewProtoP\x01ZKgoogle.golang.org/genproto/googleapis/ads/googleads/v23/resources;resources\xA2\x02\x03GAA\xAA\x02\"Google.Ads.GoogleAds.V23.Resources\xCA\x02\"Google\\Ads\\GoogleAds\\V23\\Resources\xEA\x02&Google::Ads::GoogleAds::V23::Resourcesb\x06proto3"
        , true);
        static::$is_initialized = true;
    }
}

