<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v13/resources/invoice.proto

namespace Google\Ads\GoogleAds\V13\Resources;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V13\Resources\Invoice\InvalidActivitySummary instead.
     * @deprecated
     */
    class Invoice_InvalidActivitySummary {}
}
class_exists(Invoice\InvalidActivitySummary::class);
@trigger_error('Google\Ads\GoogleAds\V13\Resources\Invoice_InvalidActivitySummary is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V13\Resources\Invoice\InvalidActivitySummary instead', E_USER_DEPRECATED);

