<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v6/errors/policy_validation_parameter_error.proto

namespace Google\Ads\GoogleAds\V6\Errors;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V6\Errors\PolicyValidationParameterErrorEnum\PolicyValidationParameterError instead.
     * @deprecated
     */
    class PolicyValidationParameterErrorEnum_PolicyValidationParameterError {}
}
class_exists(PolicyValidationParameterErrorEnum\PolicyValidationParameterError::class);
@trigger_error('Google\Ads\GoogleAds\V6\Errors\PolicyValidationParameterErrorEnum_PolicyValidationParameterError is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V6\Errors\PolicyValidationParameterErrorEnum\PolicyValidationParameterError instead', E_USER_DEPRECATED);

