<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v13/enums/linked_product_type.proto

namespace Google\Ads\GoogleAds\V13\Enums;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V13\Enums\LinkedProductTypeEnum\LinkedProductType instead.
     * @deprecated
     */
    class LinkedProductTypeEnum_LinkedProductType {}
}
class_exists(LinkedProductTypeEnum\LinkedProductType::class);
@trigger_error('Google\Ads\GoogleAds\V13\Enums\LinkedProductTypeEnum_LinkedProductType is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V13\Enums\LinkedProductTypeEnum\LinkedProductType instead', E_USER_DEPRECATED);

