<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/enums/product_type_level.proto

namespace Google\Ads\GoogleAds\V1\Enums\ProductTypeLevelEnum;

/**
 * Enum describing the level of the type of a product offer.
 *
 * Protobuf type <code>google.ads.googleads.v1.enums.ProductTypeLevelEnum.ProductTypeLevel</code>
 */
class ProductTypeLevel
{
    /**
     * Not specified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * Used for return value only. Represents value unknown in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    const UNKNOWN = 1;
    /**
     * Level 1.
     *
     * Generated from protobuf enum <code>LEVEL1 = 7;</code>
     */
    const LEVEL1 = 7;
    /**
     * Level 2.
     *
     * Generated from protobuf enum <code>LEVEL2 = 8;</code>
     */
    const LEVEL2 = 8;
    /**
     * Level 3.
     *
     * Generated from protobuf enum <code>LEVEL3 = 9;</code>
     */
    const LEVEL3 = 9;
    /**
     * Level 4.
     *
     * Generated from protobuf enum <code>LEVEL4 = 10;</code>
     */
    const LEVEL4 = 10;
    /**
     * Level 5.
     *
     * Generated from protobuf enum <code>LEVEL5 = 11;</code>
     */
    const LEVEL5 = 11;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ProductTypeLevel::class, \Google\Ads\GoogleAds\V1\Enums\ProductTypeLevelEnum_ProductTypeLevel::class);

