<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v4/enums/ad_group_ad_rotation_mode.proto

namespace Google\Ads\GoogleAds\V4\Enums;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V4\Enums\AdGroupAdRotationModeEnum\AdGroupAdRotationMode instead.
     * @deprecated
     */
    class AdGroupAdRotationModeEnum_AdGroupAdRotationMode {}
}
class_exists(AdGroupAdRotationModeEnum\AdGroupAdRotationMode::class);
@trigger_error('Google\Ads\GoogleAds\V4\Enums\AdGroupAdRotationModeEnum_AdGroupAdRotationMode is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V4\Enums\AdGroupAdRotationModeEnum\AdGroupAdRotationMode instead', E_USER_DEPRECATED);

