<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v4/enums/placeholder_type.proto

namespace Google\Ads\GoogleAds\V4\Enums;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V4\Enums\PlaceholderTypeEnum\PlaceholderType instead.
     * @deprecated
     */
    class PlaceholderTypeEnum_PlaceholderType {}
}
class_exists(PlaceholderTypeEnum\PlaceholderType::class);
@trigger_error('Google\Ads\GoogleAds\V4\Enums\PlaceholderTypeEnum_PlaceholderType is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V4\Enums\PlaceholderTypeEnum\PlaceholderType instead', E_USER_DEPRECATED);

