<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v6/enums/ad_group_criterion_approval_status.proto

namespace Google\Ads\GoogleAds\V6\Enums;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V6\Enums\AdGroupCriterionApprovalStatusEnum\AdGroupCriterionApprovalStatus instead.
     * @deprecated
     */
    class AdGroupCriterionApprovalStatusEnum_AdGroupCriterionApprovalStatus {}
}
class_exists(AdGroupCriterionApprovalStatusEnum\AdGroupCriterionApprovalStatus::class);
@trigger_error('Google\Ads\GoogleAds\V6\Enums\AdGroupCriterionApprovalStatusEnum_AdGroupCriterionApprovalStatus is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V6\Enums\AdGroupCriterionApprovalStatusEnum\AdGroupCriterionApprovalStatus instead', E_USER_DEPRECATED);

