<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v6/enums/location_extension_targeting_criterion_field.proto

namespace Google\Ads\GoogleAds\V6\Enums;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Values for Location Extension Targeting criterion fields.
 *
 * Generated from protobuf message <code>google.ads.googleads.v6.enums.LocationExtensionTargetingCriterionFieldEnum</code>
 */
class LocationExtensionTargetingCriterionFieldEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V6\Enums\LocationExtensionTargetingCriterionField::initOnce();
        parent::__construct($data);
    }

}

