<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v6/enums/product_channel_exclusivity.proto

namespace Google\Ads\GoogleAds\V6\Enums;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Availability of a product offer.
 *
 * Generated from protobuf message <code>google.ads.googleads.v6.enums.ProductChannelExclusivityEnum</code>
 */
class ProductChannelExclusivityEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V6\Enums\ProductChannelExclusivity::initOnce();
        parent::__construct($data);
    }

}

