<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v0/enums/conversion_attribution_event_type_enum.proto

namespace GPBMetadata\Google\Ads\GoogleAds\V0\Enums;

class ConversionAttributionEventTypeEnum
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0afa030a4a676f6f676c652f6164732f676f6f676c656164732f76302f65" .
            "6e756d732f636f6e76657273696f6e5f6174747269627574696f6e5f6576" .
            "656e745f747970655f656e756d2e70726f746f121d676f6f676c652e6164" .
            "732e676f6f676c656164732e76302e656e756d732285010a22436f6e7665" .
            "7273696f6e4174747269627574696f6e4576656e7454797065456e756d22" .
            "5f0a1e436f6e76657273696f6e4174747269627574696f6e4576656e7454" .
            "797065120f0a0b554e5350454349464945441000120b0a07554e4b4e4f57" .
            "4e1001120e0a0a494d5052455353494f4e1002120f0a0b494e5445524143" .
            "54494f4e100342fc010a21636f6d2e676f6f676c652e6164732e676f6f67" .
            "6c656164732e76302e656e756d734227436f6e76657273696f6e41747472" .
            "69627574696f6e4576656e7454797065456e756d50726f746f50015a4267" .
            "6f6f676c652e676f6c616e672e6f72672f67656e70726f746f2f676f6f67" .
            "6c65617069732f6164732f676f6f676c656164732f76302f656e756d733b" .
            "656e756d73a20203474141aa021d476f6f676c652e4164732e476f6f676c" .
            "654164732e56302e456e756d73ca021d476f6f676c655c4164735c476f6f" .
            "676c654164735c56305c456e756d73ea0221476f6f676c653a3a4164733a" .
            "3a476f6f676c654164733a3a56303a3a456e756d73620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

