<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v24/enums/synthetic_content_source.proto

namespace Google\Ads\GoogleAds\V24\Enums\SyntheticContentSourceEnum;

use UnexpectedValueException;

/**
 * The source of the synthetic content designation.
 *
 * Protobuf type <code>google.ads.googleads.v24.enums.SyntheticContentSourceEnum.SyntheticContentSource</code>
 */
class SyntheticContentSource
{
    /**
     * Not specified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * Used for return values only. Represents value unknown in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    const UNKNOWN = 1;
    /**
     * Attestation provided by the advertiser.
     *
     * Generated from protobuf enum <code>ADVERTISER_ATTESTED = 2;</code>
     */
    const ADVERTISER_ATTESTED = 2;
    /**
     * Google-generated content with advertiser review or input.
     *
     * Generated from protobuf enum <code>GOOGLE_GENERATED_ADVERTISER_REVIEWED = 3;</code>
     */
    const GOOGLE_GENERATED_ADVERTISER_REVIEWED = 3;
    /**
     * Google-autogenerated content without advertiser review.
     *
     * Generated from protobuf enum <code>GOOGLE_GENERATED_FULLY_AUTOMATED = 4;</code>
     */
    const GOOGLE_GENERATED_FULLY_AUTOMATED = 4;

    private static $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::UNKNOWN => 'UNKNOWN',
        self::ADVERTISER_ATTESTED => 'ADVERTISER_ATTESTED',
        self::GOOGLE_GENERATED_ADVERTISER_REVIEWED => 'GOOGLE_GENERATED_ADVERTISER_REVIEWED',
        self::GOOGLE_GENERATED_FULLY_AUTOMATED => 'GOOGLE_GENERATED_FULLY_AUTOMATED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

