<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v24/errors/campaign_draft_error.proto

namespace GPBMetadata\Google\Ads\GoogleAds\V24\Errors;

class CampaignDraftError
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();
        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xAA\x06\x0A:google/ads/googleads/v24/errors/campaign_draft_error.proto\x12\x1Fgoogle.ads.googleads.v24.errors\"\xC8\x03\x0A\x16CampaignDraftErrorEnum\"\xAD\x03\x0A\x12CampaignDraftError\x12\x0F\x0A\x0BUNSPECIFIED\x10\x00\x12\x0B\x0A\x07UNKNOWN\x10\x01\x12\x18\x0A\x14DUPLICATE_DRAFT_NAME\x10\x02\x12*\x0A&INVALID_STATUS_TRANSITION_FROM_REMOVED\x10\x03\x12+\x0A'INVALID_STATUS_TRANSITION_FROM_PROMOTED\x10\x04\x121\x0A-INVALID_STATUS_TRANSITION_FROM_PROMOTE_FAILED\x10\x05\x12 \x0A\x1CCUSTOMER_CANNOT_CREATE_DRAFT\x10\x06\x12 \x0A\x1CCAMPAIGN_CANNOT_CREATE_DRAFT\x10\x07\x12\x18\x0A\x14INVALID_DRAFT_CHANGE\x10\x08\x12\x1D\x0A\x19INVALID_STATUS_TRANSITION\x10\x09\x12-\x0A)MAX_NUMBER_OF_DRAFTS_PER_CAMPAIGN_REACHED\x10\x0A\x12'\x0A#LIST_ERRORS_FOR_PROMOTED_DRAFT_ONLY\x10\x0BB\xF7\x01\x0A#com.google.ads.googleads.v24.errorsB\x17CampaignDraftErrorProtoP\x01ZEgoogle.golang.org/genproto/googleapis/ads/googleads/v24/errors;errors\xA2\x02\x03GAA\xAA\x02\x1FGoogle.Ads.GoogleAds.V24.Errors\xCA\x02\x1FGoogle\\Ads\\GoogleAds\\V24\\Errors\xEA\x02#Google::Ads::GoogleAds::V24::Errorsb\x06proto3"
        , true);
        static::$is_initialized = true;
    }
}

