<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v24/errors/keyword_plan_error.proto

namespace GPBMetadata\Google\Ads\GoogleAds\V24\Errors;

class KeywordPlanError
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();
        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA6\x06\x0A8google/ads/googleads/v24/errors/keyword_plan_error.proto\x12\x1Fgoogle.ads.googleads.v24.errors\"\xC8\x03\x0A\x14KeywordPlanErrorEnum\"\xAF\x03\x0A\x10KeywordPlanError\x12\x0F\x0A\x0BUNSPECIFIED\x10\x00\x12\x0B\x0A\x07UNKNOWN\x10\x01\x12\x1F\x0A\x1BBID_MULTIPLIER_OUT_OF_RANGE\x10\x02\x12\x10\x0A\x0CBID_TOO_HIGH\x10\x03\x12\x0F\x0A\x0BBID_TOO_LOW\x10\x04\x12\"\x0A\x1EBID_TOO_MANY_FRACTIONAL_DIGITS\x10\x05\x12\x18\x0A\x14DAILY_BUDGET_TOO_LOW\x10\x06\x12+\x0A'DAILY_BUDGET_TOO_MANY_FRACTIONAL_DIGITS\x10\x07\x12\x11\x0A\x0DINVALID_VALUE\x10\x08\x12 \x0A\x1CKEYWORD_PLAN_HAS_NO_KEYWORDS\x10\x09\x12\x1C\x0A\x18KEYWORD_PLAN_NOT_ENABLED\x10\x0A\x12\x1A\x0A\x16KEYWORD_PLAN_NOT_FOUND\x10\x0B\x12\x0F\x0A\x0BMISSING_BID\x10\x0D\x12\x1B\x0A\x17MISSING_FORECAST_PERIOD\x10\x0E\x12\x1F\x0A\x1BINVALID_FORECAST_DATE_RANGE\x10\x0F\x12\x10\x0A\x0CINVALID_NAME\x10\x10B\xF5\x01\x0A#com.google.ads.googleads.v24.errorsB\x15KeywordPlanErrorProtoP\x01ZEgoogle.golang.org/genproto/googleapis/ads/googleads/v24/errors;errors\xA2\x02\x03GAA\xAA\x02\x1FGoogle.Ads.GoogleAds.V24.Errors\xCA\x02\x1FGoogle\\Ads\\GoogleAds\\V24\\Errors\xEA\x02#Google::Ads::GoogleAds::V24::Errorsb\x06proto3"
        , true);
        static::$is_initialized = true;
    }
}

