<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v10/enums/asset_set_asset_status.proto

namespace Google\Ads\GoogleAds\V10\Enums;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V10\Enums\AssetSetAssetStatusEnum\AssetSetAssetStatus instead.
     * @deprecated
     */
    class AssetSetAssetStatusEnum_AssetSetAssetStatus {}
}
class_exists(AssetSetAssetStatusEnum\AssetSetAssetStatus::class);
@trigger_error('Google\Ads\GoogleAds\V10\Enums\AssetSetAssetStatusEnum_AssetSetAssetStatus is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V10\Enums\AssetSetAssetStatusEnum\AssetSetAssetStatus instead', E_USER_DEPRECATED);

