<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v19/enums/ad_group_primary_status.proto

namespace Google\Ads\GoogleAds\V19\Enums;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Ad Group Primary Status. Provides insight into why an ad group is not serving
 * or not serving optimally.
 *
 * Generated from protobuf message <code>google.ads.googleads.v19.enums.AdGroupPrimaryStatusEnum</code>
 */
class AdGroupPrimaryStatusEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V19\Enums\AdGroupPrimaryStatus::initOnce();
        parent::__construct($data);
    }

}

