<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v19/enums/business_message_provider.proto

namespace Google\Ads\GoogleAds\V19\Enums;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describes business message provider types.
 *
 * Generated from protobuf message <code>google.ads.googleads.v19.enums.BusinessMessageProviderEnum</code>
 */
class BusinessMessageProviderEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V19\Enums\BusinessMessageProvider::initOnce();
        parent::__construct($data);
    }

}

