<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v24/errors/shareable_preview_error.proto

namespace Google\Ads\GoogleAds\V24\Errors\ShareablePreviewErrorEnum;

use UnexpectedValueException;

/**
 * Enum describing possible shareable preview errors.
 *
 * Protobuf type <code>google.ads.googleads.v24.errors.ShareablePreviewErrorEnum.ShareablePreviewError</code>
 */
class ShareablePreviewError
{
    /**
     * Enum unspecified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * Used for return value only. Represents value unknown in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    const UNKNOWN = 1;
    /**
     * Unsupported ad type for the given preview type.
     *
     * Generated from protobuf enum <code>UNSUPPORTED_AD_TYPE = 4;</code>
     */
    const UNSUPPORTED_AD_TYPE = 4;
    /**
     * The combined number of asset groups and ad group ads exceeds the maximum
     * of 10.
     *
     * Generated from protobuf enum <code>TOO_MANY_RESOURCES_IN_REQUEST = 6;</code>
     */
    const TOO_MANY_RESOURCES_IN_REQUEST = 6;

    private static $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::UNKNOWN => 'UNKNOWN',
        self::UNSUPPORTED_AD_TYPE => 'UNSUPPORTED_AD_TYPE',
        self::TOO_MANY_RESOURCES_IN_REQUEST => 'TOO_MANY_RESOURCES_IN_REQUEST',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

