<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v12/errors/asset_group_asset_error.proto

namespace Google\Ads\GoogleAds\V12\Errors;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Container for enum describing possible asset group asset errors.
 *
 * Generated from protobuf message <code>google.ads.googleads.v12.errors.AssetGroupAssetErrorEnum</code>
 */
class AssetGroupAssetErrorEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V12\Errors\AssetGroupAssetError::initOnce();
        parent::__construct($data);
    }

}

