<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v12/errors/conversion_goal_campaign_config_error.proto

namespace Google\Ads\GoogleAds\V12\Errors;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V12\Errors\ConversionGoalCampaignConfigErrorEnum\ConversionGoalCampaignConfigError instead.
     * @deprecated
     */
    class ConversionGoalCampaignConfigErrorEnum_ConversionGoalCampaignConfigError {}
}
class_exists(ConversionGoalCampaignConfigErrorEnum\ConversionGoalCampaignConfigError::class);
@trigger_error('Google\Ads\GoogleAds\V12\Errors\ConversionGoalCampaignConfigErrorEnum_ConversionGoalCampaignConfigError is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V12\Errors\ConversionGoalCampaignConfigErrorEnum\ConversionGoalCampaignConfigError instead', E_USER_DEPRECATED);

