<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/enums/time_type.proto

namespace Google\Ads\GoogleAds\V1\Enums\TimeTypeEnum;

/**
 * The possible time types used by certain resources as an alternative to
 * absolute timestamps.
 *
 * Protobuf type <code>google.ads.googleads.v1.enums.TimeTypeEnum.TimeType</code>
 */
class TimeType
{
    /**
     * Not specified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * Used for return value only. Represents value unknown in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    const UNKNOWN = 1;
    /**
     * As soon as possible.
     *
     * Generated from protobuf enum <code>NOW = 2;</code>
     */
    const NOW = 2;
    /**
     * An infinite point in the future.
     *
     * Generated from protobuf enum <code>FOREVER = 3;</code>
     */
    const FOREVER = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TimeType::class, \Google\Ads\GoogleAds\V1\Enums\TimeTypeEnum_TimeType::class);

