<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v19/enums/android_privacy_network_type.proto

namespace Google\Ads\GoogleAds\V19\Enums\AndroidPrivacyNetworkTypeEnum;

use UnexpectedValueException;

/**
 * Enumerates network types
 *
 * Protobuf type <code>google.ads.googleads.v19.enums.AndroidPrivacyNetworkTypeEnum.AndroidPrivacyNetworkType</code>
 */
class AndroidPrivacyNetworkType
{
    /**
     * Not specified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * The value is unknown in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    const UNKNOWN = 1;
    /**
     * Search Network.
     *
     * Generated from protobuf enum <code>SEARCH = 2;</code>
     */
    const SEARCH = 2;
    /**
     * Display Network.
     *
     * Generated from protobuf enum <code>DISPLAY = 3;</code>
     */
    const DISPLAY = 3;
    /**
     * YouTube Network.
     *
     * Generated from protobuf enum <code>YOUTUBE = 4;</code>
     */
    const YOUTUBE = 4;

    private static $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::UNKNOWN => 'UNKNOWN',
        self::SEARCH => 'SEARCH',
        self::DISPLAY => 'DISPLAY',
        self::YOUTUBE => 'YOUTUBE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AndroidPrivacyNetworkType::class, \Google\Ads\GoogleAds\V19\Enums\AndroidPrivacyNetworkTypeEnum_AndroidPrivacyNetworkType::class);

