<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v4/errors/manager_link_error.proto

namespace Google\Ads\GoogleAds\V4\Errors;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Container for enum describing possible ManagerLink errors.
 *
 * Generated from protobuf message <code>google.ads.googleads.v4.errors.ManagerLinkErrorEnum</code>
 */
class ManagerLinkErrorEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V4\Errors\ManagerLinkError::initOnce();
        parent::__construct($data);
    }

}

