<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v8/resources/recommendation.proto

namespace Google\Ads\GoogleAds\V8\Resources;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V8\Resources\Recommendation\CampaignBudgetRecommendation\CampaignBudgetRecommendationOption instead.
     * @deprecated
     */
    class Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption {}
}
class_exists(Recommendation\CampaignBudgetRecommendation\CampaignBudgetRecommendationOption::class);
@trigger_error('Google\Ads\GoogleAds\V8\Resources\Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V8\Resources\Recommendation\CampaignBudgetRecommendation\CampaignBudgetRecommendationOption instead', E_USER_DEPRECATED);

