<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v21/enums/video_ad_sequence_minimum_duration.proto

namespace Google\Ads\GoogleAds\V21\Enums;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Container for enum describing possible times after starting a video ad
 * sequence when a user is eligible to repeat the sequence.
 *
 * Generated from protobuf message <code>google.ads.googleads.v21.enums.VideoAdSequenceMinimumDurationEnum</code>
 */
class VideoAdSequenceMinimumDurationEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V21\Enums\VideoAdSequenceMinimumDuration::initOnce();
        parent::__construct($data);
    }

}

