<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v21/enums/video_ad_format_restriction.proto

namespace Google\Ads\GoogleAds\V21\Enums;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Container for enum describing format restrictions for video responsive ads in
 * video campaigns.
 *
 * Generated from protobuf message <code>google.ads.googleads.v21.enums.VideoAdFormatRestrictionEnum</code>
 */
class VideoAdFormatRestrictionEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V21\Enums\VideoAdFormatRestriction::initOnce();
        parent::__construct($data);
    }

}

