<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v3/errors/query_error.proto

namespace Google\Ads\GoogleAds\V3\Errors;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V3\Errors\QueryErrorEnum\QueryError instead.
     * @deprecated
     */
    class QueryErrorEnum_QueryError {}
}
class_exists(QueryErrorEnum\QueryError::class);
@trigger_error('Google\Ads\GoogleAds\V3\Errors\QueryErrorEnum_QueryError is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V3\Errors\QueryErrorEnum\QueryError instead', E_USER_DEPRECATED);

