<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v6/resources/hotel_performance_view.proto

namespace GPBMetadata\Google\Ads\GoogleAds\V6\Resources;

class HotelPerformanceView
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();
        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Http::initOnce();
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        $pool->internalAddGeneratedFile(
            '
ö
>google/ads/googleads/v6/resources/hotel_performance_view.proto!google.ads.googleads.v6.resourcesgoogle/api/resource.protogoogle/api/annotations.proto"Æ
HotelPerformanceViewL
resource_name (	B5àAúA/
-googleads.googleapis.com/HotelPerformanceView:`êA]
-googleads.googleapis.com/HotelPerformanceView,customers/{customer_id}/hotelPerformanceViewB†
%com.google.ads.googleads.v6.resourcesBHotelPerformanceViewProtoPZJgoogle.golang.org/genproto/googleapis/ads/googleads/v6/resources;resources¢GAAª!Google.Ads.GoogleAds.V6.ResourcesÊ!Google\\Ads\\GoogleAds\\V6\\Resourcesê%Google::Ads::GoogleAds::V6::Resourcesbproto3'
        , true);
        static::$is_initialized = true;
    }
}

