<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v6/enums/page_one_promoted_strategy_goal.proto

namespace GPBMetadata\Google\Ads\GoogleAds\V6\Enums;

class PageOnePromotedStrategyGoal
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();
        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Http::initOnce();
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            '
ä
Cgoogle/ads/googleads/v6/enums/page_one_promoted_strategy_goal.protogoogle.ads.googleads.v6.enumsBõ
!com.google.ads.googleads.v6.enumsB PageOnePromotedStrategyGoalProtoPZBgoogle.golang.org/genproto/googleapis/ads/googleads/v6/enums;enums¢GAAªGoogle.Ads.GoogleAds.V6.EnumsÊGoogle\\Ads\\GoogleAds\\V6\\Enumsê!Google::Ads::GoogleAds::V6::Enumsbproto3'
        , true);
        static::$is_initialized = true;
    }
}

