<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v22/enums/third_party_brand_safety_integration_partner.proto

namespace Google\Ads\GoogleAds\V22\Enums;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Container for enum describing available third party integration partners for
 * brand safety verification.
 *
 * Generated from protobuf message <code>google.ads.googleads.v22.enums.ThirdPartyBrandSafetyIntegrationPartnerEnum</code>
 */
class ThirdPartyBrandSafetyIntegrationPartnerEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V22\Enums\ThirdPartyBrandSafetyIntegrationPartner::initOnce();
        parent::__construct($data);
    }

}

