<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v16/common/asset_types.proto

namespace Google\Ads\GoogleAds\V16\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A hotel property asset.
 *
 * Generated from protobuf message <code>google.ads.googleads.v16.common.HotelPropertyAsset</code>
 */
class HotelPropertyAsset extends \Google\Protobuf\Internal\Message
{
    /**
     * Place IDs uniquely identify a place in the Google Places database and on
     * Google Maps. See https://developers.google.com/places/web-service/place-id
     * to learn more.
     *
     * Generated from protobuf field <code>string place_id = 1;</code>
     */
    protected $place_id = '';
    /**
     * Address of the hotel. Read-only.
     *
     * Generated from protobuf field <code>string hotel_address = 2;</code>
     */
    protected $hotel_address = '';
    /**
     * Name of the hotel. Read-only.
     *
     * Generated from protobuf field <code>string hotel_name = 3;</code>
     */
    protected $hotel_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $place_id
     *           Place IDs uniquely identify a place in the Google Places database and on
     *           Google Maps. See https://developers.google.com/places/web-service/place-id
     *           to learn more.
     *     @type string $hotel_address
     *           Address of the hotel. Read-only.
     *     @type string $hotel_name
     *           Name of the hotel. Read-only.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V16\Common\AssetTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * Place IDs uniquely identify a place in the Google Places database and on
     * Google Maps. See https://developers.google.com/places/web-service/place-id
     * to learn more.
     *
     * Generated from protobuf field <code>string place_id = 1;</code>
     * @return string
     */
    public function getPlaceId()
    {
        return $this->place_id;
    }

    /**
     * Place IDs uniquely identify a place in the Google Places database and on
     * Google Maps. See https://developers.google.com/places/web-service/place-id
     * to learn more.
     *
     * Generated from protobuf field <code>string place_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPlaceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->place_id = $var;

        return $this;
    }

    /**
     * Address of the hotel. Read-only.
     *
     * Generated from protobuf field <code>string hotel_address = 2;</code>
     * @return string
     */
    public function getHotelAddress()
    {
        return $this->hotel_address;
    }

    /**
     * Address of the hotel. Read-only.
     *
     * Generated from protobuf field <code>string hotel_address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHotelAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->hotel_address = $var;

        return $this;
    }

    /**
     * Name of the hotel. Read-only.
     *
     * Generated from protobuf field <code>string hotel_name = 3;</code>
     * @return string
     */
    public function getHotelName()
    {
        return $this->hotel_name;
    }

    /**
     * Name of the hotel. Read-only.
     *
     * Generated from protobuf field <code>string hotel_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHotelName($var)
    {
        GPBUtil::checkString($var, True);
        $this->hotel_name = $var;

        return $this;
    }

}

