<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v16/common/criteria.proto

namespace Google\Ads\GoogleAds\V16\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A Smart Campaign keyword theme.
 *
 * Generated from protobuf message <code>google.ads.googleads.v16.common.KeywordThemeInfo</code>
 */
class KeywordThemeInfo extends \Google\Protobuf\Internal\Message
{
    protected $keyword_theme;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $keyword_theme_constant
     *           The resource name of a Smart Campaign keyword theme constant.
     *           `keywordThemeConstants/{keyword_theme_id}~{sub_keyword_theme_id}`
     *     @type string $free_form_keyword_theme
     *           Free-form text to be matched to a Smart Campaign keyword theme constant
     *           on a best-effort basis.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V16\Common\Criteria::initOnce();
        parent::__construct($data);
    }

    /**
     * The resource name of a Smart Campaign keyword theme constant.
     * `keywordThemeConstants/{keyword_theme_id}~{sub_keyword_theme_id}`
     *
     * Generated from protobuf field <code>string keyword_theme_constant = 1 [(.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getKeywordThemeConstant()
    {
        return $this->readOneof(1);
    }

    public function hasKeywordThemeConstant()
    {
        return $this->hasOneof(1);
    }

    /**
     * The resource name of a Smart Campaign keyword theme constant.
     * `keywordThemeConstants/{keyword_theme_id}~{sub_keyword_theme_id}`
     *
     * Generated from protobuf field <code>string keyword_theme_constant = 1 [(.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setKeywordThemeConstant($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Free-form text to be matched to a Smart Campaign keyword theme constant
     * on a best-effort basis.
     *
     * Generated from protobuf field <code>string free_form_keyword_theme = 2;</code>
     * @return string
     */
    public function getFreeFormKeywordTheme()
    {
        return $this->readOneof(2);
    }

    public function hasFreeFormKeywordTheme()
    {
        return $this->hasOneof(2);
    }

    /**
     * Free-form text to be matched to a Smart Campaign keyword theme constant
     * on a best-effort basis.
     *
     * Generated from protobuf field <code>string free_form_keyword_theme = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFreeFormKeywordTheme($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getKeywordTheme()
    {
        return $this->whichOneof("keyword_theme");
    }

}

