<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v24/enums/conversion_action_category.proto

namespace GPBMetadata\Google\Ads\GoogleAds\V24\Enums;

class ConversionActionCategory
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();
        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xCE\x06\x0A?google/ads/googleads/v24/enums/conversion_action_category.proto\x12\x1Egoogle.ads.googleads.v24.enums\"\xE8\x03\x0A\x1CConversionActionCategoryEnum\"\xC7\x03\x0A\x18ConversionActionCategory\x12\x0F\x0A\x0BUNSPECIFIED\x10\x00\x12\x0B\x0A\x07UNKNOWN\x10\x01\x12\x0B\x0A\x07DEFAULT\x10\x02\x12\x0D\x0A\x09PAGE_VIEW\x10\x03\x12\x0C\x0A\x08PURCHASE\x10\x04\x12\x0A\x0A\x06SIGNUP\x10\x05\x12\x0C\x0A\x08DOWNLOAD\x10\x07\x12\x0F\x0A\x0BADD_TO_CART\x10\x08\x12\x12\x0A\x0EBEGIN_CHECKOUT\x10\x09\x12\x12\x0A\x0ESUBSCRIBE_PAID\x10\x0A\x12\x13\x0A\x0FPHONE_CALL_LEAD\x10\x0B\x12\x11\x0A\x0DIMPORTED_LEAD\x10\x0C\x12\x14\x0A\x10SUBMIT_LEAD_FORM\x10\x0D\x12\x14\x0A\x10BOOK_APPOINTMENT\x10\x0E\x12\x11\x0A\x0DREQUEST_QUOTE\x10\x0F\x12\x12\x0A\x0EGET_DIRECTIONS\x10\x10\x12\x12\x0A\x0EOUTBOUND_CLICK\x10\x11\x12\x0B\x0A\x07CONTACT\x10\x12\x12\x0E\x0A\x0AENGAGEMENT\x10\x13\x12\x0F\x0A\x0BSTORE_VISIT\x10\x14\x12\x0E\x0A\x0ASTORE_SALE\x10\x15\x12\x12\x0A\x0EQUALIFIED_LEAD\x10\x16\x12\x12\x0A\x0ECONVERTED_LEAD\x10\x17\x12\x1B\x0A\x17YOUTUBE_FOLLOW_ON_VIEWS\x10\x18B\xF7\x01\x0A\"com.google.ads.googleads.v24.enumsB\x1DConversionActionCategoryProtoP\x01ZCgoogle.golang.org/genproto/googleapis/ads/googleads/v24/enums;enums\xA2\x02\x03GAA\xAA\x02\x1EGoogle.Ads.GoogleAds.V24.Enums\xCA\x02\x1EGoogle\\Ads\\GoogleAds\\V24\\Enums\xEA\x02\"Google::Ads::GoogleAds::V24::Enumsb\x06proto3"
        , true);
        static::$is_initialized = true;
    }
}

