<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v24/enums/third_party_viewability_integration_partner.proto

namespace GPBMetadata\Google\Ads\GoogleAds\V24\Enums;

class ThirdPartyViewabilityIntegrationPartner
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();
        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA8\x04\x0APgoogle/ads/googleads/v24/enums/third_party_viewability_integration_partner.proto\x12\x1Egoogle.ads.googleads.v24.enums\"\xA2\x01\x0A+ThirdPartyViewabilityIntegrationPartnerEnum\"s\x0A'ThirdPartyViewabilityIntegrationPartner\x12\x0F\x0A\x0BUNSPECIFIED\x10\x00\x12\x0B\x0A\x07UNKNOWN\x10\x01\x12\x11\x0A\x0DDOUBLE_VERIFY\x10\x02\x12\x17\x0A\x13INTEGRAL_AD_SCIENCE\x10\x03B\x86\x02\x0A\"com.google.ads.googleads.v24.enumsB,ThirdPartyViewabilityIntegrationPartnerProtoP\x01ZCgoogle.golang.org/genproto/googleapis/ads/googleads/v24/enums;enums\xA2\x02\x03GAA\xAA\x02\x1EGoogle.Ads.GoogleAds.V24.Enums\xCA\x02\x1EGoogle\\Ads\\GoogleAds\\V24\\Enums\xEA\x02\"Google::Ads::GoogleAds::V24::Enumsb\x06proto3"
        , true);
        static::$is_initialized = true;
    }
}

