<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/enums/simulation_type.proto

namespace GPBMetadata\Google\Ads\GoogleAds\V1\Enums;

class SimulationType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9f030a33676f6f676c652f6164732f676f6f676c656164732f76312f65" .
            "6e756d732f73696d756c6174696f6e5f747970652e70726f746f121d676f" .
            "6f676c652e6164732e676f6f676c656164732e76312e656e756d7322560a" .
            "1253696d756c6174696f6e54797065456e756d22400a0e53696d756c6174" .
            "696f6e54797065120f0a0b554e5350454349464945441000120b0a07554e" .
            "4b4e4f574e100112100a0c4249445f4d4f444946494552100542e8010a21" .
            "636f6d2e676f6f676c652e6164732e676f6f676c656164732e76312e656e" .
            "756d73421353696d756c6174696f6e5479706550726f746f50015a42676f" .
            "6f676c652e676f6c616e672e6f72672f67656e70726f746f2f676f6f676c" .
            "65617069732f6164732f676f6f676c656164732f76312f656e756d733b65" .
            "6e756d73a20203474141aa021d476f6f676c652e4164732e476f6f676c65" .
            "4164732e56312e456e756d73ca021d476f6f676c655c4164735c476f6f67" .
            "6c654164735c56315c456e756d73ea0221476f6f676c653a3a4164733a3a" .
            "476f6f676c654164733a3a56313a3a456e756d73620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

