<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v8/enums/lead_form_field_user_input_type.proto

namespace Google\Ads\GoogleAds\V8\Enums;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V8\Enums\LeadFormFieldUserInputTypeEnum\LeadFormFieldUserInputType instead.
     * @deprecated
     */
    class LeadFormFieldUserInputTypeEnum_LeadFormFieldUserInputType {}
}
class_exists(LeadFormFieldUserInputTypeEnum\LeadFormFieldUserInputType::class);
@trigger_error('Google\Ads\GoogleAds\V8\Enums\LeadFormFieldUserInputTypeEnum_LeadFormFieldUserInputType is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V8\Enums\LeadFormFieldUserInputTypeEnum\LeadFormFieldUserInputType instead', E_USER_DEPRECATED);

