<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v8/enums/lead_form_post_submit_call_to_action_type.proto

namespace Google\Ads\GoogleAds\V8\Enums;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describes the type of post-submit call-to-action phrases for a lead form.
 *
 * Generated from protobuf message <code>google.ads.googleads.v8.enums.LeadFormPostSubmitCallToActionTypeEnum</code>
 */
class LeadFormPostSubmitCallToActionTypeEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V8\Enums\LeadFormPostSubmitCallToActionType::initOnce();
        parent::__construct($data);
    }

}

