<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v18/resources/local_services_verification_artifact.proto

namespace Google\Ads\GoogleAds\V18\Resources;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A proto holding information specific to a local services insurance.
 *
 * Generated from protobuf message <code>google.ads.googleads.v18.resources.InsuranceVerificationArtifact</code>
 */
class InsuranceVerificationArtifact extends \Google\Protobuf\Internal\Message
{
    /**
     * Output only. Insurance amount. This is measured in "micros" of the currency
     * mentioned in the insurance document.
     *
     * Generated from protobuf field <code>optional int64 amount_micros = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $amount_micros = null;
    /**
     * Output only. Insurance document's rejection reason.
     *
     * Generated from protobuf field <code>optional .google.ads.googleads.v18.enums.LocalServicesInsuranceRejectionReasonEnum.LocalServicesInsuranceRejectionReason rejection_reason = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $rejection_reason = null;
    /**
     * Output only. The readonly field containing the information for an uploaded
     * insurance document.
     *
     * Generated from protobuf field <code>optional .google.ads.googleads.v18.common.LocalServicesDocumentReadOnly insurance_document_readonly = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $insurance_document_readonly = null;
    /**
     * Output only. The timestamp when this insurance expires.
     * The format is "YYYY-MM-DD HH:MM:SS" in the Google Ads account's timezone.
     * Examples: "2018-03-05 09:15:00" or "2018-02-01 14:34:30"
     *
     * Generated from protobuf field <code>optional string expiration_date_time = 4 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $expiration_date_time = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $amount_micros
     *           Output only. Insurance amount. This is measured in "micros" of the currency
     *           mentioned in the insurance document.
     *     @type int $rejection_reason
     *           Output only. Insurance document's rejection reason.
     *     @type \Google\Ads\GoogleAds\V18\Common\LocalServicesDocumentReadOnly $insurance_document_readonly
     *           Output only. The readonly field containing the information for an uploaded
     *           insurance document.
     *     @type string $expiration_date_time
     *           Output only. The timestamp when this insurance expires.
     *           The format is "YYYY-MM-DD HH:MM:SS" in the Google Ads account's timezone.
     *           Examples: "2018-03-05 09:15:00" or "2018-02-01 14:34:30"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V18\Resources\LocalServicesVerificationArtifact::initOnce();
        parent::__construct($data);
    }

    /**
     * Output only. Insurance amount. This is measured in "micros" of the currency
     * mentioned in the insurance document.
     *
     * Generated from protobuf field <code>optional int64 amount_micros = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return int|string
     */
    public function getAmountMicros()
    {
        return isset($this->amount_micros) ? $this->amount_micros : 0;
    }

    public function hasAmountMicros()
    {
        return isset($this->amount_micros);
    }

    public function clearAmountMicros()
    {
        unset($this->amount_micros);
    }

    /**
     * Output only. Insurance amount. This is measured in "micros" of the currency
     * mentioned in the insurance document.
     *
     * Generated from protobuf field <code>optional int64 amount_micros = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmountMicros($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount_micros = $var;

        return $this;
    }

    /**
     * Output only. Insurance document's rejection reason.
     *
     * Generated from protobuf field <code>optional .google.ads.googleads.v18.enums.LocalServicesInsuranceRejectionReasonEnum.LocalServicesInsuranceRejectionReason rejection_reason = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return int
     */
    public function getRejectionReason()
    {
        return isset($this->rejection_reason) ? $this->rejection_reason : 0;
    }

    public function hasRejectionReason()
    {
        return isset($this->rejection_reason);
    }

    public function clearRejectionReason()
    {
        unset($this->rejection_reason);
    }

    /**
     * Output only. Insurance document's rejection reason.
     *
     * Generated from protobuf field <code>optional .google.ads.googleads.v18.enums.LocalServicesInsuranceRejectionReasonEnum.LocalServicesInsuranceRejectionReason rejection_reason = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param int $var
     * @return $this
     */
    public function setRejectionReason($var)
    {
        GPBUtil::checkEnum($var, \Google\Ads\GoogleAds\V18\Enums\LocalServicesInsuranceRejectionReasonEnum\LocalServicesInsuranceRejectionReason::class);
        $this->rejection_reason = $var;

        return $this;
    }

    /**
     * Output only. The readonly field containing the information for an uploaded
     * insurance document.
     *
     * Generated from protobuf field <code>optional .google.ads.googleads.v18.common.LocalServicesDocumentReadOnly insurance_document_readonly = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return \Google\Ads\GoogleAds\V18\Common\LocalServicesDocumentReadOnly|null
     */
    public function getInsuranceDocumentReadonly()
    {
        return $this->insurance_document_readonly;
    }

    public function hasInsuranceDocumentReadonly()
    {
        return isset($this->insurance_document_readonly);
    }

    public function clearInsuranceDocumentReadonly()
    {
        unset($this->insurance_document_readonly);
    }

    /**
     * Output only. The readonly field containing the information for an uploaded
     * insurance document.
     *
     * Generated from protobuf field <code>optional .google.ads.googleads.v18.common.LocalServicesDocumentReadOnly insurance_document_readonly = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param \Google\Ads\GoogleAds\V18\Common\LocalServicesDocumentReadOnly $var
     * @return $this
     */
    public function setInsuranceDocumentReadonly($var)
    {
        GPBUtil::checkMessage($var, \Google\Ads\GoogleAds\V18\Common\LocalServicesDocumentReadOnly::class);
        $this->insurance_document_readonly = $var;

        return $this;
    }

    /**
     * Output only. The timestamp when this insurance expires.
     * The format is "YYYY-MM-DD HH:MM:SS" in the Google Ads account's timezone.
     * Examples: "2018-03-05 09:15:00" or "2018-02-01 14:34:30"
     *
     * Generated from protobuf field <code>optional string expiration_date_time = 4 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getExpirationDateTime()
    {
        return isset($this->expiration_date_time) ? $this->expiration_date_time : '';
    }

    public function hasExpirationDateTime()
    {
        return isset($this->expiration_date_time);
    }

    public function clearExpirationDateTime()
    {
        unset($this->expiration_date_time);
    }

    /**
     * Output only. The timestamp when this insurance expires.
     * The format is "YYYY-MM-DD HH:MM:SS" in the Google Ads account's timezone.
     * Examples: "2018-03-05 09:15:00" or "2018-02-01 14:34:30"
     *
     * Generated from protobuf field <code>optional string expiration_date_time = 4 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setExpirationDateTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->expiration_date_time = $var;

        return $this;
    }

}

