<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/enums/location_extension_targeting_criterion_field.proto

namespace Google\Ads\GoogleAds\V1\Enums\LocationExtensionTargetingCriterionFieldEnum;

/**
 * Possible values for Location Extension Targeting criterion fields.
 *
 * Protobuf type <code>google.ads.googleads.v1.enums.LocationExtensionTargetingCriterionFieldEnum.LocationExtensionTargetingCriterionField</code>
 */
class LocationExtensionTargetingCriterionField
{
    /**
     * Not specified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * Used for return value only. Represents value unknown in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    const UNKNOWN = 1;
    /**
     * Data Type: STRING. Line 1 of the business address.
     *
     * Generated from protobuf enum <code>ADDRESS_LINE_1 = 2;</code>
     */
    const ADDRESS_LINE_1 = 2;
    /**
     * Data Type: STRING. Line 2 of the business address.
     *
     * Generated from protobuf enum <code>ADDRESS_LINE_2 = 3;</code>
     */
    const ADDRESS_LINE_2 = 3;
    /**
     * Data Type: STRING. City of the business address.
     *
     * Generated from protobuf enum <code>CITY = 4;</code>
     */
    const CITY = 4;
    /**
     * Data Type: STRING. Province of the business address.
     *
     * Generated from protobuf enum <code>PROVINCE = 5;</code>
     */
    const PROVINCE = 5;
    /**
     * Data Type: STRING. Postal code of the business address.
     *
     * Generated from protobuf enum <code>POSTAL_CODE = 6;</code>
     */
    const POSTAL_CODE = 6;
    /**
     * Data Type: STRING. Country code of the business address.
     *
     * Generated from protobuf enum <code>COUNTRY_CODE = 7;</code>
     */
    const COUNTRY_CODE = 7;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(LocationExtensionTargetingCriterionField::class, \Google\Ads\GoogleAds\V1\Enums\LocationExtensionTargetingCriterionFieldEnum_LocationExtensionTargetingCriterionField::class);

