<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v12/common/policy.proto

namespace Google\Ads\GoogleAds\V12\Common;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V12\Common\PolicyTopicEvidence\DestinationNotWorking instead.
     * @deprecated
     */
    class PolicyTopicEvidence_DestinationNotWorking {}
}
class_exists(PolicyTopicEvidence\DestinationNotWorking::class);
@trigger_error('Google\Ads\GoogleAds\V12\Common\PolicyTopicEvidence_DestinationNotWorking is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V12\Common\PolicyTopicEvidence\DestinationNotWorking instead', E_USER_DEPRECATED);

