<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/services/detail_placement_view_service.proto

namespace GPBMetadata\Google\Ads\GoogleAds\V1\Services;

class DetailPlacementViewService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Ads\GoogleAds\V1\Resources\DetailPlacementView::initOnce();
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a97030a44676f6f676c652f6164732f676f6f676c656164732f76312f73" .
            "657276696365732f64657461696c5f706c6163656d656e745f766965775f" .
            "736572766963652e70726f746f1220676f6f676c652e6164732e676f6f67" .
            "6c656164732e76312e73657276696365731a1c676f6f676c652f6170692f" .
            "616e6e6f746174696f6e732e70726f746f4286020a24636f6d2e676f6f67" .
            "6c652e6164732e676f6f676c656164732e76312e7365727669636573421f" .
            "44657461696c506c6163656d656e74566965775365727669636550726f74" .
            "6f50015a48676f6f676c652e676f6c616e672e6f72672f67656e70726f74" .
            "6f2f676f6f676c65617069732f6164732f676f6f676c656164732f76312f" .
            "73657276696365733b7365727669636573a20203474141aa0220476f6f67" .
            "6c652e4164732e476f6f676c654164732e56312e5365727669636573ca02" .
            "20476f6f676c655c4164735c476f6f676c654164735c56315c5365727669" .
            "636573ea0224476f6f676c653a3a4164733a3a476f6f676c654164733a3a" .
            "56313a3a5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

