<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v24/common/experiment_types.proto

namespace Google\Ads\GoogleAds\V24\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Configuration for a Video experiment.
 *
 * Generated from protobuf message <code>google.ads.googleads.v24.common.VideoExperimentInfo</code>
 */
class VideoExperimentInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * The subtype of the Video experiment.
     *
     * Generated from protobuf field <code>.google.ads.googleads.v24.enums.VideoExperimentSubtypeEnum.VideoExperimentSubtype video_experiment_subtype = 1;</code>
     */
    protected $video_experiment_subtype = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $video_experiment_subtype
     *           The subtype of the Video experiment.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V24\Common\ExperimentTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * The subtype of the Video experiment.
     *
     * Generated from protobuf field <code>.google.ads.googleads.v24.enums.VideoExperimentSubtypeEnum.VideoExperimentSubtype video_experiment_subtype = 1;</code>
     * @return int
     */
    public function getVideoExperimentSubtype()
    {
        return $this->video_experiment_subtype;
    }

    /**
     * The subtype of the Video experiment.
     *
     * Generated from protobuf field <code>.google.ads.googleads.v24.enums.VideoExperimentSubtypeEnum.VideoExperimentSubtype video_experiment_subtype = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVideoExperimentSubtype($var)
    {
        GPBUtil::checkEnum($var, \Google\Ads\GoogleAds\V24\Enums\VideoExperimentSubtypeEnum\VideoExperimentSubtype::class);
        $this->video_experiment_subtype = $var;

        return $this;
    }

}

