<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v11/enums/ad_group_criterion_status.proto

namespace Google\Ads\GoogleAds\V11\Enums;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message describing AdGroupCriterion statuses.
 *
 * Generated from protobuf message <code>google.ads.googleads.v11.enums.AdGroupCriterionStatusEnum</code>
 */
class AdGroupCriterionStatusEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V11\Enums\AdGroupCriterionStatus::initOnce();
        parent::__construct($data);
    }

}

