<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v11/enums/geo_targeting_restriction.proto

namespace Google\Ads\GoogleAds\V11\Enums;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V11\Enums\GeoTargetingRestrictionEnum\GeoTargetingRestriction instead.
     * @deprecated
     */
    class GeoTargetingRestrictionEnum_GeoTargetingRestriction {}
}
class_exists(GeoTargetingRestrictionEnum\GeoTargetingRestriction::class);
@trigger_error('Google\Ads\GoogleAds\V11\Enums\GeoTargetingRestrictionEnum_GeoTargetingRestriction is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V11\Enums\GeoTargetingRestrictionEnum\GeoTargetingRestriction instead', E_USER_DEPRECATED);

