<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v18/resources/recommendation.proto

namespace Google\Ads\GoogleAds\V18\Resources\Recommendation\KeywordRecommendation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Information about a search term as related to a keyword recommendation.
 *
 * Generated from protobuf message <code>google.ads.googleads.v18.resources.Recommendation.KeywordRecommendation.SearchTerm</code>
 */
class SearchTerm extends \Google\Protobuf\Internal\Message
{
    /**
     * Output only. The text of the search term.
     *
     * Generated from protobuf field <code>string text = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $text = '';
    /**
     * Output only. Estimated number of historical weekly searches for this
     * search term.
     *
     * Generated from protobuf field <code>int64 estimated_weekly_search_count = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $estimated_weekly_search_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $text
     *           Output only. The text of the search term.
     *     @type int|string $estimated_weekly_search_count
     *           Output only. Estimated number of historical weekly searches for this
     *           search term.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V18\Resources\Recommendation::initOnce();
        parent::__construct($data);
    }

    /**
     * Output only. The text of the search term.
     *
     * Generated from protobuf field <code>string text = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Output only. The text of the search term.
     *
     * Generated from protobuf field <code>string text = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

    /**
     * Output only. Estimated number of historical weekly searches for this
     * search term.
     *
     * Generated from protobuf field <code>int64 estimated_weekly_search_count = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return int|string
     */
    public function getEstimatedWeeklySearchCount()
    {
        return $this->estimated_weekly_search_count;
    }

    /**
     * Output only. Estimated number of historical weekly searches for this
     * search term.
     *
     * Generated from protobuf field <code>int64 estimated_weekly_search_count = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param int|string $var
     * @return $this
     */
    public function setEstimatedWeeklySearchCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->estimated_weekly_search_count = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SearchTerm::class, \Google\Ads\GoogleAds\V18\Resources\Recommendation_KeywordRecommendation_SearchTerm::class);

