<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v10/errors/audience_error.proto

namespace Google\Ads\GoogleAds\V10\Errors\AudienceErrorEnum;

use UnexpectedValueException;

/**
 * Enum describing possible audience errors.
 *
 * Protobuf type <code>google.ads.googleads.v10.errors.AudienceErrorEnum.AudienceError</code>
 */
class AudienceError
{
    /**
     * Enum unspecified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * The received error code is not known in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    const UNKNOWN = 1;
    /**
     * An audience with this name already exists.
     *
     * Generated from protobuf enum <code>NAME_ALREADY_IN_USE = 2;</code>
     */
    const NAME_ALREADY_IN_USE = 2;
    /**
     * A dimension within the audience definition is not valid.
     *
     * Generated from protobuf enum <code>DIMENSION_INVALID = 3;</code>
     */
    const DIMENSION_INVALID = 3;

    private static $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::UNKNOWN => 'UNKNOWN',
        self::NAME_ALREADY_IN_USE => 'NAME_ALREADY_IN_USE',
        self::DIMENSION_INVALID => 'DIMENSION_INVALID',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AudienceError::class, \Google\Ads\GoogleAds\V10\Errors\AudienceErrorEnum_AudienceError::class);

