<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v6/services/income_range_view_service.proto

namespace GPBMetadata\Google\Ads\GoogleAds\V6\Services;

class IncomeRangeViewService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();
        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Http::initOnce();
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        \GPBMetadata\Google\Api\Client::initOnce();
        $pool->internalAddGeneratedFile(
            '
ˆ
9google/ads/googleads/v6/resources/income_range_view.proto!google.ads.googleads.v6.resourcesgoogle/api/resource.protogoogle/api/annotations.proto"–
IncomeRangeViewG
resource_name (	B0‡A˙A*
(googleads.googleapis.com/IncomeRangeView:tÍAq
(googleads.googleapis.com/IncomeRangeViewEcustomers/{customer_id}/incomeRangeViews/{ad_group_id}~{criterion_id}BÅ
%com.google.ads.googleads.v6.resourcesBIncomeRangeViewProtoPZJgoogle.golang.org/genproto/googleapis/ads/googleads/v6/resources;resources¢GAA™!Google.Ads.GoogleAds.V6.Resources !Google\\Ads\\GoogleAds\\V6\\ResourcesÍ%Google::Ads::GoogleAds::V6::Resourcesbproto3
Ä
@google/ads/googleads/v6/services/income_range_view_service.proto google.ads.googleads.v6.servicesgoogle/api/annotations.protogoogle/api/client.protogoogle/api/field_behavior.protogoogle/api/resource.proto"d
GetIncomeRangeViewRequestG
resource_name (	B0‡A˙A*
(googleads.googleapis.com/IncomeRangeView2≥
IncomeRangeViewService—
GetIncomeRangeView;.google.ads.googleads.v6.services.GetIncomeRangeViewRequest2.google.ads.googleads.v6.resources.IncomeRangeView"JÇ”‰ì42/v6/{resource_name=customers/*/incomeRangeViews/*}⁄Aresource_nameE Agoogleads.googleapis.com“A\'https://www.googleapis.com/auth/adwordsBÇ
$com.google.ads.googleads.v6.servicesBIncomeRangeViewServiceProtoPZHgoogle.golang.org/genproto/googleapis/ads/googleads/v6/services;services¢GAA™ Google.Ads.GoogleAds.V6.Services  Google\\Ads\\GoogleAds\\V6\\ServicesÍ$Google::Ads::GoogleAds::V6::Servicesbproto3'
        , true);
        static::$is_initialized = true;
    }
}

