<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v0/common/criteria.proto

namespace Google\Ads\GoogleAds\V0\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A location criterion.
 *
 * Generated from protobuf message <code>google.ads.googleads.v0.common.LocationInfo</code>
 */
class LocationInfo extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Google\Ads\GoogleAds\V0\Common\Criteria::initOnce();
        parent::__construct();
    }

}

