<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v0/common/ad_type_infos.proto

namespace Google\Ads\GoogleAds\V0\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A video ad.
 *
 * Generated from protobuf message <code>google.ads.googleads.v0.common.VideoAdInfo</code>
 */
class VideoAdInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * The MediaFile resource to use for the video.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue media_file = 1;</code>
     */
    private $media_file = null;
    protected $format;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\StringValue $media_file
     *           The MediaFile resource to use for the video.
     *     @type \Google\Ads\GoogleAds\V0\Common\VideoTrueViewInStreamAdInfo $in_stream
     *           Video TrueView in-stream format.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V0\Common\AdTypeInfos::initOnce();
        parent::__construct($data);
    }

    /**
     * The MediaFile resource to use for the video.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue media_file = 1;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getMediaFile()
    {
        return $this->media_file;
    }

    /**
     * The MediaFile resource to use for the video.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue media_file = 1;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setMediaFile($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->media_file = $var;

        return $this;
    }

    /**
     * Video TrueView in-stream format.
     *
     * Generated from protobuf field <code>.google.ads.googleads.v0.common.VideoTrueViewInStreamAdInfo in_stream = 2;</code>
     * @return \Google\Ads\GoogleAds\V0\Common\VideoTrueViewInStreamAdInfo
     */
    public function getInStream()
    {
        return $this->readOneof(2);
    }

    /**
     * Video TrueView in-stream format.
     *
     * Generated from protobuf field <code>.google.ads.googleads.v0.common.VideoTrueViewInStreamAdInfo in_stream = 2;</code>
     * @param \Google\Ads\GoogleAds\V0\Common\VideoTrueViewInStreamAdInfo $var
     * @return $this
     */
    public function setInStream($var)
    {
        GPBUtil::checkMessage($var, \Google\Ads\GoogleAds\V0\Common\VideoTrueViewInStreamAdInfo::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getFormat()
    {
        return $this->whichOneof("format");
    }

}

