<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/enums/campaign_experiment_status.proto

namespace Google\Ads\GoogleAds\V1\Enums;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V1\Enums\CampaignExperimentStatusEnum\CampaignExperimentStatus instead.
     * @deprecated
     */
    class CampaignExperimentStatusEnum_CampaignExperimentStatus {}
}
class_exists(CampaignExperimentStatusEnum\CampaignExperimentStatus::class);
@trigger_error('Google\Ads\GoogleAds\V1\Enums\CampaignExperimentStatusEnum_CampaignExperimentStatus is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V1\Enums\CampaignExperimentStatusEnum\CampaignExperimentStatus instead', E_USER_DEPRECATED);

