<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v1/enums/campaign_status.proto

namespace Google\Ads\GoogleAds\V1\Enums;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V1\Enums\CampaignStatusEnum\CampaignStatus instead.
     * @deprecated
     */
    class CampaignStatusEnum_CampaignStatus {}
}
class_exists(CampaignStatusEnum\CampaignStatus::class);
@trigger_error('Google\Ads\GoogleAds\V1\Enums\CampaignStatusEnum_CampaignStatus is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V1\Enums\CampaignStatusEnum\CampaignStatus instead', E_USER_DEPRECATED);

