<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v18/enums/shared_set_status.proto

namespace Google\Ads\GoogleAds\V18\Enums;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Container for enum describing types of shared set statuses.
 *
 * Generated from protobuf message <code>google.ads.googleads.v18.enums.SharedSetStatusEnum</code>
 */
class SharedSetStatusEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V18\Enums\SharedSetStatus::initOnce();
        parent::__construct($data);
    }

}

