<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v3/enums/app_campaign_app_store.proto

namespace Google\Ads\GoogleAds\V3\Enums;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V3\Enums\AppCampaignAppStoreEnum\AppCampaignAppStore instead.
     * @deprecated
     */
    class AppCampaignAppStoreEnum_AppCampaignAppStore {}
}
class_exists(AppCampaignAppStoreEnum\AppCampaignAppStore::class);
@trigger_error('Google\Ads\GoogleAds\V3\Enums\AppCampaignAppStoreEnum_AppCampaignAppStore is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V3\Enums\AppCampaignAppStoreEnum\AppCampaignAppStore instead', E_USER_DEPRECATED);

