<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v3/enums/callout_placeholder_field.proto

namespace Google\Ads\GoogleAds\V3\Enums;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Values for Callout placeholder fields.
 *
 * Generated from protobuf message <code>google.ads.googleads.v3.enums.CalloutPlaceholderFieldEnum</code>
 */
class CalloutPlaceholderFieldEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V3\Enums\CalloutPlaceholderField::initOnce();
        parent::__construct($data);
    }

}

