<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v3/enums/custom_placeholder_field.proto

namespace Google\Ads\GoogleAds\V3\Enums;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V3\Enums\CustomPlaceholderFieldEnum\CustomPlaceholderField instead.
     * @deprecated
     */
    class CustomPlaceholderFieldEnum_CustomPlaceholderField {}
}
class_exists(CustomPlaceholderFieldEnum\CustomPlaceholderField::class);
@trigger_error('Google\Ads\GoogleAds\V3\Enums\CustomPlaceholderFieldEnum_CustomPlaceholderField is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V3\Enums\CustomPlaceholderFieldEnum\CustomPlaceholderField instead', E_USER_DEPRECATED);

