<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v3/enums/data_driven_model_status.proto

namespace Google\Ads\GoogleAds\V3\Enums;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Container for enum indicating data driven model status.
 *
 * Generated from protobuf message <code>google.ads.googleads.v3.enums.DataDrivenModelStatusEnum</code>
 */
class DataDrivenModelStatusEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V3\Enums\DataDrivenModelStatus::initOnce();
        parent::__construct($data);
    }

}

