<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v3/enums/offline_user_data_job_status.proto

namespace Google\Ads\GoogleAds\V3\Enums;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Container for enum describing status of an offline user data job.
 *
 * Generated from protobuf message <code>google.ads.googleads.v3.enums.OfflineUserDataJobStatusEnum</code>
 */
class OfflineUserDataJobStatusEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V3\Enums\OfflineUserDataJobStatus::initOnce();
        parent::__construct($data);
    }

}

