<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v3/enums/simulation_modification_method.proto

namespace Google\Ads\GoogleAds\V3\Enums;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Container for enum describing the method by which a simulation modifies
 * a field.
 *
 * Generated from protobuf message <code>google.ads.googleads.v3.enums.SimulationModificationMethodEnum</code>
 */
class SimulationModificationMethodEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V3\Enums\SimulationModificationMethod::initOnce();
        parent::__construct($data);
    }

}

