<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v3/enums/webpage_condition_operator.proto

namespace Google\Ads\GoogleAds\V3\Enums;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Container for enum describing webpage condition operator in webpage
 * criterion.
 *
 * Generated from protobuf message <code>google.ads.googleads.v3.enums.WebpageConditionOperatorEnum</code>
 */
class WebpageConditionOperatorEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V3\Enums\WebpageConditionOperator::initOnce();
        parent::__construct($data);
    }

}

