<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v0/errors/change_status_error.proto

namespace GPBMetadata\Google\Ads\GoogleAds\V0\Errors;

class ChangeStatusError
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aad030a38676f6f676c652f6164732f676f6f676c656164732f76302f65" .
            "72726f72732f6368616e67655f7374617475735f6572726f722e70726f74" .
            "6f121e676f6f676c652e6164732e676f6f676c656164732e76302e657272" .
            "6f7273227a0a154368616e67655374617475734572726f72456e756d2261" .
            "0a114368616e67655374617475734572726f72120f0a0b554e5350454349" .
            "464945441000120b0a07554e4b4e4f574e100112160a12494e56414c4944" .
            "5f53544152545f44415445100212160a1253544152545f444154455f544f" .
            "4f5f4f4c44100342cc010a22636f6d2e676f6f676c652e6164732e676f6f" .
            "676c656164732e76302e6572726f727342164368616e6765537461747573" .
            "4572726f7250726f746f50015a44676f6f676c652e676f6c616e672e6f72" .
            "672f67656e70726f746f2f676f6f676c65617069732f6164732f676f6f67" .
            "6c656164732f76302f6572726f72733b6572726f7273a20203474141aa02" .
            "1e476f6f676c652e4164732e476f6f676c654164732e56302e4572726f72" .
            "73ca021e476f6f676c655c4164735c476f6f676c654164735c56305c4572" .
            "726f7273620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

