<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v12/resources/campaign.proto

namespace Google\Ads\GoogleAds\V12\Resources;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V12\Resources\Campaign\LocalServicesCampaignSettings instead.
     * @deprecated
     */
    class Campaign_LocalServicesCampaignSettings {}
}
class_exists(Campaign\LocalServicesCampaignSettings::class);
@trigger_error('Google\Ads\GoogleAds\V12\Resources\Campaign_LocalServicesCampaignSettings is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V12\Resources\Campaign\LocalServicesCampaignSettings instead', E_USER_DEPRECATED);

