<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v9/enums/listing_group_filter_bidding_category_level.proto

namespace Google\Ads\GoogleAds\V9\Enums;

if (false) {
    /**
     * This class is deprecated. Use Google\Ads\GoogleAds\V9\Enums\ListingGroupFilterBiddingCategoryLevelEnum\ListingGroupFilterBiddingCategoryLevel instead.
     * @deprecated
     */
    class ListingGroupFilterBiddingCategoryLevelEnum_ListingGroupFilterBiddingCategoryLevel {}
}
class_exists(ListingGroupFilterBiddingCategoryLevelEnum\ListingGroupFilterBiddingCategoryLevel::class);
@trigger_error('Google\Ads\GoogleAds\V9\Enums\ListingGroupFilterBiddingCategoryLevelEnum_ListingGroupFilterBiddingCategoryLevel is deprecated and will be removed in the next major release. Use Google\Ads\GoogleAds\V9\Enums\ListingGroupFilterBiddingCategoryLevelEnum\ListingGroupFilterBiddingCategoryLevel instead', E_USER_DEPRECATED);

