<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v9/enums/summary_row_setting.proto

namespace Google\Ads\GoogleAds\V9\Enums;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Indicates summary row setting in request parameter.
 *
 * Generated from protobuf message <code>google.ads.googleads.v9.enums.SummaryRowSettingEnum</code>
 */
class SummaryRowSettingEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\GoogleAds\V9\Enums\SummaryRowSetting::initOnce();
        parent::__construct($data);
    }

}

